### PR TITLE
Target .NET 6

### PR DESCRIPTION
**Pull request by jetersen**

### CODE REVIEW

**Comment by jetersen** [comment]
@patriksvensson seems like actions is not enabled on the repo 🗡️

I decided to update all dependencies while upgrading to .NET 6

**Comment by VisualBean** [comment]
global.json still reports 5.0.100 which means you cannot run this tool for .net 6.0 without installing .net 5 first..

**Comment by jetersen** [comment]
@patriksvensson would be nice to get this updated ? :)

**Review by patriksvensson — APPROVED** [review]

**Comment by patriksvensson** [comment]
@jetersen Sorry for taking so long. Merged.

Thank you! 👍

**Pull request merged**
