### PR TITLE
Add ability to scan sequentially all projects of a solution

### PR DESCRIPTION
**Pull request by TheFireCookie**
- Scan all the CSPROJ
- Produces a final report with all the snitchable projects
- One test to cover the feature

### CODE REVIEW

**Comment by patriksvensson** [comment]
@TheFireCookie Thanks for this! I'm currently planning something similar, but this takes us 90% of where we want to go 👍

**Comment by TheFireCookie** [comment]
@patriksvensson when will you release a new version of Snitch then? :)

**Comment by patriksvensson** [comment]
Probably sometime tonight (UTC). Doing the last work on some changes 🙂

**Comment by patriksvensson** [comment]
@TheFireCookie Version 1.6.0 is now released

**Pull request merged**
